CREATE TABLE T_ORDER (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	CUSTOMER_ID BIGINT,
	STATE VARCHAR(255),
	AMOUNT BIGINT,
	constraint PK_ORDER primary key (ID),
	constraint FK_ORDER_CUSTOMERID foreign key (CUSTOMER_ID) references T_CUSTOMER
);
